### ISSUE TITLE
does an object having a `@@enter` method mean that defining it with var/let/const would throw an error?

### ISSUE THREAD

**Issue by nektro** [rbuckton/proposal-using-enforcement#3]
is being able to enforce that a goal of the proposal or any others?

**Comment by rbuckton** [comment]
No, any change to `var`/`let`/`const` would introduce a runtime penalty to existing code that does not employ `using`. Instead, enforcement is achieved by introducing a stumbling block when using `var`/`let`/`const` that is streamlined with `using`:

```ts
var res1 = getResourceWithUsingEnforcement();
res1.doAThing(); // throws at runtime since `res2` is not the actual resource

var res2 = getResourceWithUsingEnforcement()[Symbol.enter]();
res2.doAThing(); // works, but you had to perform the explicit step of 
                 // invoking `[Symbol.enter]()` to get here

using res3 = getResourceWithUsingEnforcement();
res3.doAThing(); // works since the unwrapping is performed for you
```

The upshot is that documentation for an API with strict enforcement will likely only depict `using` in its examples, and thus would catch anyone who mistranscribes `using` as `var`/`let`/`const`.

**Comment by rbuckton** [comment]
Closing as there is no specific issue to be addressed and the question asked has been answered.

**Comment by nektro** [comment]
ah I see, makes a ton of sense. thanks!
